### ISSUE TITLE
JsonObject Error

### ISSUE THREAD

**Issue by stephenstubbs** [jklingsporn/vertx-jooq-async#3]
I am getting this error cannot find symbol symbol:   class JsonObject on generated DAOS. Have you run into this issue before?

**Comment by stephenstubbs** [comment]
if I looks like there is an import missing in FutureAsyncVertxGenerator.java where you generate DAO imports for JsonObject. Am I missing something or does this need to be fixed?

**Comment by jklingsporn** [comment]
Sorry I'm currently on vacation. Will look into it next week.


Am 11.08.2017 12:09 nachm. schrieb "sstubbs" <notifications@github.com>:

**Comment by jklingsporn** [comment]
Thanks for reporting. Fix will be ready tomorrow.
